api/urls.py
from django.conf.urls import include, url
from api.views import *

urlpatterns = [
    # Examples:
    # url(r'^$', 'wechat_server.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^phone/$', PhoneBindView.as_view()),
]

page/urls.py
from django.conf.urls import include, url
from page.views import *

urlpatterns = [
    # Examples:
    # url(r'^$', 'wechat_server.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^phone/$', PhonePageView.as_view()),
    url(r'^hint/$', HintPageView.as_view()),
    url(r'^result/$', PhoneListView.as_view()),
    url(r'^shops/$', ShopListView.as_view()),
]

service/urls.py
from django.conf.urls import include, url
from service.views import *

urlpatterns = [
    # Examples:
    # url(r'^$', 'wechat_server.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^sxrhy/$', MainServiceView.as_view()),
]

wechat_server/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from wechat_server import settings

urlpatterns = [
    # Examples:
    # url(r'^$', 'wechat_server.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/v1/', include('api.urls')),
    url(r'^service/v1/', include('service.urls')),
    url(r'^page/', include('page.urls')),
    url(r'^s/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_MEDIA}),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_MEDIA}),
]

core/models.py
# coding: utf-8
from __future__ import unicode_literals
from django.db import models


# Create your models here.
class BaseModel(models.Model):
    create_time = models.DateTimeField(auto_now_add=True)
    modify_time = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class UniqueCode(BaseModel):
    code_choices = (
        (1, '10元电子券'),
        (2, '30元电子券'),
        (3, '50元电子券'),
        (4, '60元电子券'),
        (10, '导航'),
        (11, '测试'),

    )
    unique_id = models.CharField(max_length=64, unique=True)
    code_type = models.IntegerField(default=1, choices=code_choices)
    qr_content = models.CharField(max_length=256, default='', null=True, blank=True)
    qr_url = models.CharField(max_length=256, default='', null=True, blank=True)
    phone = models.CharField(max_length=20, default='', null=True, blank=True)
    use = models.BooleanField(default=False)

    def __unicode__(self):
        return '{0}-{1}-{2}-{3}'.format(self.unique_id, self.qr_content, self.use, self.phone)


class WeChatAdmin(models.Model):
    name = models.CharField(max_length=128, default='', null=True, blank=True)
    app_id = models.CharField(max_length=128, default='', null=True, blank=True)
    app_secret = models.CharField(max_length=128, default='', null=True, blank=True)
    access_token = models.CharField(max_length=1024, default='', null=True, blank=True)

    def __unicode__(self):
        return self.app_id


class Shop(models.Model):
    name = models.CharField(max_length=20)
    address = models.CharField(max_length=100, default='', null=True, blank=True)
    url = models.CharField(max_length=128, default='', null=True, blank=True)

    def __unicode__(self):
        return self.name

page/models.py
from django.db import models

# Create your models here.

api/views.py
# coding: utf-8
from __future__ import unicode_literals

from django.http import HttpResponse
from django.views.generic import DetailView
from django.views.generic import ListView

from core.Mixin.StatusWrapMixin import StatusWrapMixin, ERROR_DATA
from core.dss.Mixin import JsonResponseMixin, MultipleJsonResponseMixin
from core.models import UniqueCode


class PhoneBindView(StatusWrapMixin, JsonResponseMixin, DetailView):
    model = UniqueCode
    include_attr = ['code']

    def get(self, request, *args, **kwargs):
        phone = request.GET.get('phone')
        token = request.GET.get('token')
        unique_code_list = UniqueCode.objects.filter(unique_id=token, use=False).all()
        phone_nums = UniqueCode.objects.filter(phone=phone).count()
        if unique_code_list.exists() and phone_nums < 2:
            unique_code = unique_code_list[0]
            unique_code.phone = phone
            unique_code.use = True
            if unique_code.code_type != 11:
                unique_code.save()
            # self.message = unique_code.code_type
            scode_type = {1: '10', 2: '30', 3: '50', 4: '60', 11: '50'}
            self.message = '成功领取{0}元电子券!'.format(scode_type.get(unique_code.code_type))
            return self.render_to_response({})
        self.message = '领券超出限制或无效'
        self.status_code = ERROR_DATA
        return self.render_to_response({})

core/views.py
from django.shortcuts import render

# Create your views here.

page/views.py
# coding: utf-8
from __future__ import unicode_literals

from django.http import HttpResponse
from django.views.generic import ListView
from django.views.generic import TemplateView

from core.models import UniqueCode, Shop


class PhonePageView(TemplateView):
    template_name = 'phone.html'

    def get_context_data(self, **kwargs):
        context = super(PhonePageView, self).get_context_data(**kwargs)
        token = self.request.GET.get('token', '')
        context['token'] = token
        context['title'] = '优惠券领取'
        return context


class HintPageView(TemplateView):
    template_name = 'hint.html'


class ShopListView(ListView):
    model = Shop
    template_name = 'shop.html'


class PhoneListView(ListView):
    template_name = 'hint.html'
    model = UniqueCode

    def get(self, request, *args, **kwargs):
        code_type = {1: '10元电子券', 2: '30元电子券', 3: '50元电子券', 4: '60元电子券'}
        queryset = self.get_queryset().filter(use=True).exclude(code_type__in=(10, 11)).order_by(
            '-modify_time')
        content = '时间 电话 优惠券<br>'
        for query in queryset:
            q_str = '{0} {1} {2}<br>'.format(query.modify_time.strftime('%Y-%m-%d %H:%M:%S'), query.phone, code_type.get(query.code_type, '未知'))
            content = '{0}{1}'.format(content, q_str)
        return HttpResponse(content)

service/views.py
# coding: utf-8
from __future__ import unicode_literals

from django.http import HttpResponse
from django.views.generic import DetailView

from core.Mixin.StatusWrapMixin import StatusWrapMixin, ERROR_DATA
from core.dss.Mixin import JsonResponseMixin
from core.models import UniqueCode
from core.wechat_service import WeChatService


class MainServiceView(StatusWrapMixin, JsonResponseMixin, DetailView):
    model = UniqueCode
    include_attr = ['code']

    def get(self, request, *args, **kwargs):
        WS = WeChatService('wx586e2dfae97146a7', '226f8be53f435e54247470a39f907ec6')
        signature = request.GET.get('signature', '')  # Request 中 GET 参数 signature
        timestamp = request.GET.get('timestamp', '')  # Request 中 GET 参数 timestamp
        nonce = request.GET.get('nonce', '')
        echostr = request.GET.get('echostr', '')
        if WS.wechat.check_signature(signature, timestamp, nonce):
            return HttpResponse(echostr)
        return HttpResponse(echostr)

    def post(self, request, *args, **kwargs):
        WS = WeChatService('wx586e2dfae97146a7', '226f8be53f435e54247470a39f907ec6')
        body_text = request.body
        response = WS.message_manage(body_text)
        return HttpResponse(response)

templates/hint.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0">
    <title>领券说明</title>
    <link href="/s/css/style.css" rel="stylesheet">
</head>
<body>
<div class="topArea">
    <img src="/s/image/bg.png">
{#    <p>填写手机号</p>#}
</div>
<div class="hintArea">
{#    <div class="title">&#183;&nbsp;如&nbsp;何&nbsp;领&nbsp;券&nbsp;&#183;</div>#}
{#    <div class="content">#}
{#        <ul>#}
{#            <li>1.扫码关注"中油好客e站"</li>#}
{#            <li>2.在公众号菜单点击右下角"更多",即可查看"我的电子券"</li>#}
{#            <li>3.显示出来即是领取成功</li>#}
{#            <li>4.所有电子券都将在确认领取成功后三天内发放</li>#}
{#        </ul>#}
{#        <img src="/s/image/qr.png">#}
{#        <span>中油好客e站</span>#}
{#    </div>#}
    <img src="/s/image/info.png" alt="info" class="content">
</div>
</body>
</html>

templates/phone.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0">
    <title>{{ title }}</title>
    <link href="/s/css/style.css" rel="stylesheet">
</head>
<body>
<div class="topArea">
    <img src="/s/image/bg.png">
    <p>填写手机号</p>
</div>
<div class="submitArea">
    <input placeholder="请输入手机号" type="number" id="phone">
    <input type="hidden" id="token" value="{{ token }}">
    <button id="submit">立即领取</button>
</div>
<script src="/s/js/query.js" type="text/javascript"></script>
</body>
</html>

templates/shop.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta charset="utf-8">
    <meta name="viewport"
          content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, initial-scale=1.0, user-scalable=no">
    <title>门店导航</title>
    <!-- 引入 FrozenUI -->
    <link rel="stylesheet" href="http://i.gtimg.cn/vipstyle/frozenui/2.0.0/css/frozen.css"/>
    {#    <style type="text/css">#}
    {#        a:after {#}
    {#            font-family: iconarrow !important;#}
    {#            font-size: 32px;#}
    {#            line-height: 50px;#}
    {#            font-style: normal;#}
    {#            -webkit-font-smoothing: antialiased;#}
    {#            -webkit-text-stroke-width: .2px;#}
    {#            display: block;#}
    {#            color: #c7c7c7;#}
    {#            content: "\f000";#}
    {#            position: absolute;#}
    {#            right: 12px;#}
    {#            top: 50%;#}
    {#            margin-top: -25px;#}
    {#            margin-right: -11px;#}
    {#        }#}
    {#    </style>#}
</head>
<body>
<ul class="ui-list ui-list-nospace ui-border-tb">
    {% for shop in shop_list %}
        <li class="ui-border-t ui-arrowlink">
            <div class="ui-list-info">
                <a href="{{ shop.url }}">
                    <h4 class="ui-nowrap">{{ shop.name }}</h4>
                    <p class="ui-nowrap">{{ shop.address }}</p>
                </a>
            </div>
        </li>
    {% endfor %}
</ul>
</body>
</html>